### PR TITLE
choo@6, bankai@6, style tweaks

### PR DESCRIPTION
**Pull request by ungoldman**
This PR bumps choo and bankai to v6 and updates the site code to use the newer APIs. Also tweaked the styles for the index a bit. Hope you like it!

If you'd prefer I break this out into two PRs (one for version bumps, one for style) I can do that too, just did this quickly on my lunch break today.

localhost-8080- laptop with hidpi screen 1

### CODE REVIEW

**Comment by toddself** [comment]
dang this looks good!

**Comment by ungoldman** [comment]
Rebased after merging #10

**Review by bcomnes — APPROVED** [review]
> yoshuawuyts: ungoldman: neat!
02:20 ungoldman: would be cool to get the weird kerning back at some point; but what you got is better than the broken version currently live. Merge away!

**Comment by ungoldman** [comment]
Ok, added letter spacing back to `choo` in the title by popular demand, and tweaked footer to be same width as rest of sections. Looks alright when emulating mobile styles and I got the ok from #choo channel so I'm merging away.

w o  o 🎉

**Comment by bcomnes** [comment]
It looks like dho o now that I see it again

**Pull request merged**
