### PR TITLE
Docs corrections

### PR DESCRIPTION
**Pull request by achou11**
I made some grammatical edits to the docs sections. If I wasn't super sure about the correctness of something, I left it alone - so my edits aren't super strict or thorough. I primarily looked to change anything that made the readability a little awkward for me.

I really love reading all of the content for the docs and learning more about how to use Choo! Hoping to make more contributions in the future :)

### CODE REVIEW

**Review by yoshuawuyts — APPROVED** [review]
These look great!

**Comment by yoshuawuyts** [comment]
@achou11 these look really good, thanks for all your work! -- I'm a bit hesitant to merge right now though because our deploy pipeline is broken, which means that merging will take the website offline haha. But leaving this as "approved & should be merged as soon as we get the pipeline fixed"!

**Comment by achou11** [comment]
haha no problem! thanks for reviewing :)

**Comment by goto-bus-stop** [comment]
choo 6.10 broke it by changing stores to lazy initialisation. hypha initialises routes inside a store. https://github.com/choojs/bankai/pull/452 would fix it on the bankai end.

**Pull request merged**
