### PR TITLE
Fixes #8 switch to fade over blink

### LINKED ISSUE #8: VHS flicker is painful, possibly harmful
The "VHS flicker" on page load hurts my eyes, and is possibly a danger for folks with epilepsy. A safer alternative could be simply fading the text in rather than flickering. Or skipping it altogether.

### PR DESCRIPTION
**Pull request by wavebeem**
Pretty simple, just change the blinking to a fade effect. Let me know what you think! 😄

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Hey, thanks for putting the effort in! - I feel the fade is a lil linear right now; perhaps if we make the fade a bit softer (like with the word "choo") it'll look a lil smoother?

**Comment by wavebeem** [comment]
So maybe a longer duration and a different animation timing function?

**Comment by yoshuawuyts** [comment]
Yeah sounds good!

**Comment by wavebeem** [comment]
Tell me what you think about this style. It's almost as showy as the blink but without being as painful to look at.

**Comment by ungoldman** [comment]
Looks great to me! https://deploy-preview-9--choo.netlify.com/

@yoshuawuyts any reason not to merge this?

**Review by yoshuawuyts — APPROVED** [review]
oops, this slipped through. Thanks heaps for the patch! :D

**Comment by wavebeem** [comment]
Yay

**Pull request merged**
